# 2.0.0

Breaking change: logError gets passed a second "req" argument
